name: fastapi_template CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run yapf in diff mode and pylint.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: actions/setup-python@v2
        with:
            python-verion: 3.8
      - name: Lint
        run: |
            make lint
      - name: Upload pylint.txt
        uses: actions/upload-artifact@v1
        with:
          name: pylint
          path: pylint.txt

  unittest-coverage:
    name: Run unittest and generate code coverage report.

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_template
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.8 for unitttests.
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Run unittests
        run: |
            make test
            bash <(curl -s https://codecov.io/bash)
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: fastapi_template
            POSTGRES_HOST: localhost
